### ISSUE TITLE
[Q] Alt-t as a shortcut in keymaps

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [bus-stop/terminus#137]
### I would like to be able do use `alt-t` as a shortcut to open a new terminal
>   'alt-t': 'terminus:new'

When i add the line above in the terminus.cson file, the shortcut doesn't work. I've tried several combinations of `alt-` with any key, it never seem to work. Other combinations of keys are properly working.

Is it even possible to have `alt-[something]` as a shortcut ?

**Comment by UziTech** [comment]
I'm not sure where you got the `terminus.cson` file but here is information on how to create keymaps in Atom.

https://flight-manual.atom.io/behind-atom/sections/keymaps-in-depth/

**Comment by JeSuisUnCaillou** [comment]
Oh right, thanks for pointing me back to this :facepalm:
