### ISSUE TITLE
[BR] The terminal not work after atom upgrade to 1.52.0.

### ISSUE THREAD

**Issue by Yoshinosido** [bus-stop/terminus#138]
- [ ] I have reset Atom to defaults prior to submitting report.
- [ ] I have not reset Atom to defaults prior to submitting report.
- [ ] I have tried uninstalling/reinstalling the terminal.
- [ ] I have not tried uninstalling/reinstalling the terminal.
### Description

The terminal not work after atom upgrade to 1.52.0.
### Steps to reproduce

1.Open terminal and it just blank.
2.
3.

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

### Versions

```
> atom --version
1.52.0

```
```
> apm --version
2.5.2

```
OS name and version:
Terminal version:

**Comment by the-j0k3r** [comment]
Atom1.52.0 has electron 6.x, and apm/nody-gyp have no idea how to upgrade modules properly

to fix, manually remove `~/atom/packages/terminus` and then reinstall.

Nothing we can do about apm/node-gyp failures either, these are Atoms projects.
