### ISSUE TITLE
Python command "python --version" in atom terminal not working

### ISSUE THREAD

**Issue by cdacones** [bus-stop/terminus#169]
I recently downloaded Python 3.9.1

When I use the command in Windows PowerShell on my laptop, the version is displayed, but when I use the Windows PowerShell-like atom terminal, the command doesn't work at all. There are no error messages but nothing shows up. Python was added to the PATH during installation for the user variables, but I'm not sure if it's also supposed to be added to the system variables or if the terminus package doesn't support this version.

**Comment by cdacones** [comment]
I figured it out. I just discovered Atom needs to be in administrator mode to use the terminal.

**Comment by the-j0k3r** [comment]
>  I just discovered Atom needs to be in administrator mode to use the terminal.

Not really the case, why would you need Atom to run as admin? You need to add any env variables in Terminus settings that arent being read from default path.

See the gif  for location of setting. **Shell Environment Variables**

![generic](https://user-images.githubusercontent.com/31389848/101464287-bdccc000-393e-11eb-8569-60cabb43a00b.gif)
