### ISSUE TITLE
Need Rebuild  "node-pty-prebuilt-multiarch" to get normative terminus compiled. 

### ISSUE THREAD

**Issue by thiagolucio** [bus-stop/terminus#219]
OS: Fedora x86_64 
  Model: Latitude 3400 
  Kernel: 5.11.13-200.fc33.x86_64 
  Shell: /bin/bash 5.0.17 
  CPU: Intel i5-8265U (8) @ 3.900GHz [64.0°on] 
  Memory: 5369MiB / 15872MiB 
  GPU: Intel WhiskeyLake-U GT2 [UHD Graphics 620] 
  Resolution: 2560x1080 

### I get this error when update Atom Last Stable Version (1.56.0) today:

![terminus-error-atom1 56](https://user-images.githubusercontent.com/5756266/114870685-d8bcae80-9dce-11eb-97ba-fb3e90e12c40.png)

## Solution:

To solve this problem, I access this package "node-pty-prebuilt-multiarch" inside my Linux OS "home" in ".atom/packages/terminus/node_modules/node-pty-prebuilt-multiarch" and run "npm install" and "npm run build" and inside atom after this, click in "rebuild" button to fix this error. 

### POI:
- I think to solve this, just rebuild this package before publishing this extension. 

Thanks a \o/ for your extension and Be safe all!

**Comment by UziTech** [comment]
> I think to solve this, just rebuild this package before publishing this extension.

`node-pty-prebuilt-multiarch` is a dependency that is installed and built when terminus is installed. This isn't something terminus can fix. Any time Atom updates the bundled version of node you will have to rebuild any package that contains native modules.

**Comment by thiagolucio** [comment]
> > I think to solve this, just rebuild this package before publishing this extension.
> 
> `node-pty-prebuilt-multiarch` is a dependency that is installed and built when terminus is installed. This isn't something terminus can fix. Any time Atom updates the bundled version of the node you will have to rebuild any package that contains native modules.

Yes. I understand. Thanks for the explanation.  
Closed now. 
Be safe.

**Comment by the-j0k3r** [comment]
@thiagolucio see https://github.com/atom/atom/pull/21927 which will fix such issues in future.
