### ISSUE TITLE
ANNOUNCEMENT:  Terminus going out in a blaze of glory.

### ISSUE THREAD

**Issue by the-j0k3r** [bus-stop/terminus#329]
### I would like to be able do the following

The issue is regarding the last commit

https://github.com/bus-stop/terminus/runs/5520361306?check_suite_focus=true

Error: Deprecated function HTMLDocument.registerElement was called.

### Additional context

Clearly the beta Atom deprecates this needs to be updated?

@UziTech thoughts/help

**Comment by UziTech** [comment]
We will have to move to [customElements.define](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define)

**Comment by UziTech** [comment]
it looks like the `registerElement` call comes from `atom-space-pen-views` . We will have to find a different dependency.

**Comment by the-j0k3r** [comment]
There is also the option of retiring this project when that time comes, both term.js and atom-space-pen-views haven't had any development in years.

I no longer have the time, due to real life issues both personally and professionally or the JS knowledge to undertake this task, which will likely require a re-write on both fronts, and depending on your kind contributions solely doesn't seem fair.

I'm OK with whatever you decide though, Your kindness, skills and time were and will always be sincerely appreciated. Thanks for everything @UziTech and apologies for this.

**Comment by UziTech** [comment]
I was kind of thinking the same thing. I always use x-terminal and I would think adding the necessary features to that from terminus would be easier than moving terminus to use x-term and update the views.

**Comment by the-j0k3r** [comment]
Indeed, x-terminal would be better for it as well.

Also I think its best to archive the project when that time comes,to prevent issue ticket noise that will undoubtedly ensue, I'll update the readme to reflect this now while while I can.

Thanks again for helping this project remain alive as long as it was.

**Comment by the-j0k3r** [comment]
I was hoping with https://github.com/bus-stop/terminus/commit/5b414a5cf3b011d0a9d5ea22872b613d3ff34004 that a new release would be made, in order to push the readme changes to https://atom.io/packages/terminus but seems it got skipped somehow.

Yelp.

**Comment by the-j0k3r** [comment]
I think https://github.com/bus-stop/terminus/commit/3a25b056206593df9e34a4f55d1adaba38dcfb48 may do it, lets see.

**Comment by the-j0k3r** [comment]
Sorted.
