### ISSUE TITLE
[BR] typo in keymaps/terminus.cson

### ISSUE THREAD

**Issue by PerBothner** [bus-stop/terminus#55]
Replace `shit` by `shift` in:

      'cmd-shit-i': 'terminus:insert-text'
      'alt-shit-i': 'terminus:insert-text'

**Comment by the-j0k3r** [comment]
Hello @PerBothner and thank you for bringing this to our attention, should be fixed now a relase will shortly be auto pushed.

You see what happens when coffee isn't consumed =)
