### ISSUE TITLE
[Q] Failed to install, any help?

### ISSUE THREAD

**Issue by MarcusAlmert** [bus-stop/terminus#79]
> apm install terminus

 returns: 
>node-pty-prebuilt-multiarch@0.9.0 install /tmp/apm-install-dir-120324-323183-pd5v4o.ga2n/node_modules/terminus/node_modules/node-pty-prebuilt-multiarch
prebuild-install || node scripts/install.js
Aborted (core dumped)
Aborted (core dumped)
gyp: Call to 'node -e "require('nan')"' returned exit status 134 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 5.4.0-26-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-120324-323183-pd5v4o.ga2n/node_modules/terminus/node_modules/node-pty-prebuilt-multiarch
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
Aborted (core dumped)
Aborted (core dumped)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-120324-323183-pd5v4o.ga2n/package.json'
npm WARN apm-install-dir-120324-323183-pd5v4o.ga2n No description
npm WARN apm-install-dir-120324-323183-pd5v4o.ga2n No repository field.
npm WARN apm-install-dir-120324-323183-pd5v4o.ga2n No README data
npm WARN apm-install-dir-120324-323183-pd5v4o.ga2n No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! node-pty-prebuilt-multiarch@0.9.0 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the node-pty-prebuilt-multiarch@0.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marcus/.atom/.apm/_logs/2020-04-24T00_01_56_462Z-debug.log

Im runnung Ubuntu 20.04.

**Comment by MarcusAlmert** [comment]
Doing a manual install from git with:

> git clone <package-repo>
cd package-name
apm install
apm link

is working.
I think it could have something to do with [Python error in atom.](https://github.com/atom/atom/issues/20585) 
This could come from the usage of `node-gyp` which depends on python.

**Comment by the-j0k3r** [comment]
I dont accept this kind of bug reports by ignoring the issue templates.

node gyp/python is not related to terminus its apm related in any case, we dont support apm bugs in any case.

If you are looking to get support fill in the issue template in its entirety, only then we can triage the issue properly and provide a better response to your issue...

until then marking this as invalid and response needed from you.

**Comment by the-j0k3r** [comment]
Also the node-gyp version apm uses requires python2 Ubuntu 20.04 doesnt have python2 anymore.

Im closing this really, Theres nothing to be done in this project.
