### ISSUE TITLE
[Q] How do I change the theme?

### ISSUE THREAD

**Issue by bradlefler** [bus-stop/terminus#92]
Hello! Sorry, I'm kind of new to all of this. How do I change the terminal theme? I am on ubuntu if that helps.

**Comment by UziTech** [comment]
1. Open command palette (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>P</kbd>)
![image](https://user-images.githubusercontent.com/97994/84941455-0ea5df00-b0a7-11ea-88c5-322836fb424b.png)
2. Search for `Settings View: View Installed Packages`
![image](https://user-images.githubusercontent.com/97994/84941556-2da47100-b0a7-11ea-9d9e-1e19854198b9.png)
3. Search for `terminus` 
![image](https://user-images.githubusercontent.com/97994/84941567-339a5200-b0a7-11ea-8a86-946b7034714b.png)
4. Click `Settings`
![image](https://user-images.githubusercontent.com/97994/84941604-3eed7d80-b0a7-11ea-959f-8d69a064c10f.png)
5. Change the `Theme` setting
![image](https://user-images.githubusercontent.com/97994/84942145-05694200-b0a8-11ea-9359-b2570e210a26.png)

**Comment by bradlefler** [comment]
Thanks!
